//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoogleSearchAPI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CountryCode {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CountryCode() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GoogleSearchAPI.Resources.CountryCode", typeof(CountryCode).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to af.
        /// </summary>
        public static string Afghanistan {
            get {
                return ResourceManager.GetString("Afghanistan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ax.
        /// </summary>
        public static string Åland_Islands {
            get {
                return ResourceManager.GetString("Åland_Islands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to al.
        /// </summary>
        public static string Albania {
            get {
                return ResourceManager.GetString("Albania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dz.
        /// </summary>
        public static string Algeria {
            get {
                return ResourceManager.GetString("Algeria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to as.
        /// </summary>
        public static string American_Samoa {
            get {
                return ResourceManager.GetString("American_Samoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ad.
        /// </summary>
        public static string Andorra {
            get {
                return ResourceManager.GetString("Andorra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ao.
        /// </summary>
        public static string Angola {
            get {
                return ResourceManager.GetString("Angola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ai.
        /// </summary>
        public static string Anguilla {
            get {
                return ResourceManager.GetString("Anguilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aq.
        /// </summary>
        public static string Antarctica {
            get {
                return ResourceManager.GetString("Antarctica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ag.
        /// </summary>
        public static string Antigua_and_Barbuda {
            get {
                return ResourceManager.GetString("Antigua_and_Barbuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ar.
        /// </summary>
        public static string Argentina {
            get {
                return ResourceManager.GetString("Argentina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to am.
        /// </summary>
        public static string Armenia {
            get {
                return ResourceManager.GetString("Armenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aw.
        /// </summary>
        public static string Aruba {
            get {
                return ResourceManager.GetString("Aruba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to au.
        /// </summary>
        public static string australia {
            get {
                return ResourceManager.GetString("australia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at.
        /// </summary>
        public static string austria {
            get {
                return ResourceManager.GetString("austria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to az.
        /// </summary>
        public static string Azerbaijan {
            get {
                return ResourceManager.GetString("Azerbaijan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bs.
        /// </summary>
        public static string Bahamas {
            get {
                return ResourceManager.GetString("Bahamas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bh.
        /// </summary>
        public static string Bahrain {
            get {
                return ResourceManager.GetString("Bahrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bd.
        /// </summary>
        public static string Bangladesh {
            get {
                return ResourceManager.GetString("Bangladesh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bb.
        /// </summary>
        public static string Barbados {
            get {
                return ResourceManager.GetString("Barbados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by.
        /// </summary>
        public static string Belarus {
            get {
                return ResourceManager.GetString("Belarus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to be.
        /// </summary>
        public static string Belgium {
            get {
                return ResourceManager.GetString("Belgium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bz.
        /// </summary>
        public static string Belize {
            get {
                return ResourceManager.GetString("Belize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bj.
        /// </summary>
        public static string Benin {
            get {
                return ResourceManager.GetString("Benin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bm.
        /// </summary>
        public static string Bermuda {
            get {
                return ResourceManager.GetString("Bermuda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bt.
        /// </summary>
        public static string Bhutan {
            get {
                return ResourceManager.GetString("Bhutan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bo.
        /// </summary>
        public static string Bolivia {
            get {
                return ResourceManager.GetString("Bolivia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ba.
        /// </summary>
        public static string Bosnia {
            get {
                return ResourceManager.GetString("Bosnia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bw.
        /// </summary>
        public static string Botswana {
            get {
                return ResourceManager.GetString("Botswana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bv.
        /// </summary>
        public static string Bouvet_Island {
            get {
                return ResourceManager.GetString("Bouvet_Island", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to br.
        /// </summary>
        public static string Brazil {
            get {
                return ResourceManager.GetString("Brazil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to io.
        /// </summary>
        public static string British_Indian_Ocean_Territory {
            get {
                return ResourceManager.GetString("British_Indian_Ocean_Territory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bn.
        /// </summary>
        public static string Brunei_Daryssalam {
            get {
                return ResourceManager.GetString("Brunei_Daryssalam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bg.
        /// </summary>
        public static string Bulgaria {
            get {
                return ResourceManager.GetString("Bulgaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bf.
        /// </summary>
        public static string Burkina_Faso {
            get {
                return ResourceManager.GetString("Burkina_Faso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bi.
        /// </summary>
        public static string Burunudi {
            get {
                return ResourceManager.GetString("Burunudi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kh.
        /// </summary>
        public static string Cambodia {
            get {
                return ResourceManager.GetString("Cambodia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cm.
        /// </summary>
        public static string Cameroon {
            get {
                return ResourceManager.GetString("Cameroon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ca.
        /// </summary>
        public static string Canada {
            get {
                return ResourceManager.GetString("Canada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cv.
        /// </summary>
        public static string Cape_Verde {
            get {
                return ResourceManager.GetString("Cape_Verde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ky.
        /// </summary>
        public static string Cayman_Islands {
            get {
                return ResourceManager.GetString("Cayman_Islands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cf.
        /// </summary>
        public static string Central_African_Republic {
            get {
                return ResourceManager.GetString("Central_African_Republic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td.
        /// </summary>
        public static string Chad {
            get {
                return ResourceManager.GetString("Chad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cl.
        /// </summary>
        public static string Chile {
            get {
                return ResourceManager.GetString("Chile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cn.
        /// </summary>
        public static string China {
            get {
                return ResourceManager.GetString("China", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cx.
        /// </summary>
        public static string Christmas_Island {
            get {
                return ResourceManager.GetString("Christmas_Island", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cc.
        /// </summary>
        public static string Cocos_Islands {
            get {
                return ResourceManager.GetString("Cocos_Islands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to co.
        /// </summary>
        public static string Colombia {
            get {
                return ResourceManager.GetString("Colombia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to km.
        /// </summary>
        public static string Comoros {
            get {
                return ResourceManager.GetString("Comoros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cg.
        /// </summary>
        public static string Congo {
            get {
                return ResourceManager.GetString("Congo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cd.
        /// </summary>
        public static string Congo_Democratic_Republic {
            get {
                return ResourceManager.GetString("Congo_Democratic_Republic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ck.
        /// </summary>
        public static string Cook_Islands {
            get {
                return ResourceManager.GetString("Cook_Islands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cr.
        /// </summary>
        public static string Costa_Rica {
            get {
                return ResourceManager.GetString("Costa_Rica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ci.
        /// </summary>
        public static string Cote_dlvoire {
            get {
                return ResourceManager.GetString("Cote_dlvoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hr.
        /// </summary>
        public static string Croatia {
            get {
                return ResourceManager.GetString("Croatia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cu.
        /// </summary>
        public static string Cuba {
            get {
                return ResourceManager.GetString("Cuba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cy.
        /// </summary>
        public static string Cyprus {
            get {
                return ResourceManager.GetString("Cyprus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cz.
        /// </summary>
        public static string Czech_Republic {
            get {
                return ResourceManager.GetString("Czech_Republic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dk.
        /// </summary>
        public static string Denmark {
            get {
                return ResourceManager.GetString("Denmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dj.
        /// </summary>
        public static string Djibouti {
            get {
                return ResourceManager.GetString("Djibouti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dm.
        /// </summary>
        public static string Dominica {
            get {
                return ResourceManager.GetString("Dominica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to do.
        /// </summary>
        public static string Dominican_Republic {
            get {
                return ResourceManager.GetString("Dominican_Republic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ec.
        /// </summary>
        public static string Ecuador {
            get {
                return ResourceManager.GetString("Ecuador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eg.
        /// </summary>
        public static string Egypt {
            get {
                return ResourceManager.GetString("Egypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sv.
        /// </summary>
        public static string El_Salvador {
            get {
                return ResourceManager.GetString("El_Salvador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gq.
        /// </summary>
        public static string Equatorial_Guinea {
            get {
                return ResourceManager.GetString("Equatorial_Guinea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to er.
        /// </summary>
        public static string Eritrea {
            get {
                return ResourceManager.GetString("Eritrea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ee.
        /// </summary>
        public static string Estonia {
            get {
                return ResourceManager.GetString("Estonia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to et.
        /// </summary>
        public static string Ethiopia {
            get {
                return ResourceManager.GetString("Ethiopia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fk.
        /// </summary>
        public static string Falkland_Islands_Malvinas {
            get {
                return ResourceManager.GetString("Falkland_Islands_Malvinas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fo.
        /// </summary>
        public static string Faroe_Islands {
            get {
                return ResourceManager.GetString("Faroe_Islands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fj.
        /// </summary>
        public static string Fiji {
            get {
                return ResourceManager.GetString("Fiji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fi.
        /// </summary>
        public static string Finland {
            get {
                return ResourceManager.GetString("Finland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fr.
        /// </summary>
        public static string France {
            get {
                return ResourceManager.GetString("France", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gf.
        /// </summary>
        public static string French_Guiana {
            get {
                return ResourceManager.GetString("French_Guiana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pf.
        /// </summary>
        public static string French_Polynesia {
            get {
                return ResourceManager.GetString("French_Polynesia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tf.
        /// </summary>
        public static string French_Southern_Territories {
            get {
                return ResourceManager.GetString("French_Southern_Territories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ga.
        /// </summary>
        public static string Gabon {
            get {
                return ResourceManager.GetString("Gabon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gm.
        /// </summary>
        public static string Gambia {
            get {
                return ResourceManager.GetString("Gambia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ge.
        /// </summary>
        public static string Georgia {
            get {
                return ResourceManager.GetString("Georgia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gh.
        /// </summary>
        public static string Ghana {
            get {
                return ResourceManager.GetString("Ghana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gi.
        /// </summary>
        public static string Gibraltar {
            get {
                return ResourceManager.GetString("Gibraltar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gr.
        /// </summary>
        public static string Greece {
            get {
                return ResourceManager.GetString("Greece", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gl.
        /// </summary>
        public static string Greenland {
            get {
                return ResourceManager.GetString("Greenland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gd.
        /// </summary>
        public static string Grenada {
            get {
                return ResourceManager.GetString("Grenada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gp.
        /// </summary>
        public static string Guadeloupe {
            get {
                return ResourceManager.GetString("Guadeloupe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gu.
        /// </summary>
        public static string Guam {
            get {
                return ResourceManager.GetString("Guam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gt.
        /// </summary>
        public static string Guatemala {
            get {
                return ResourceManager.GetString("Guatemala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gg.
        /// </summary>
        public static string Guernsey {
            get {
                return ResourceManager.GetString("Guernsey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gn.
        /// </summary>
        public static string Guinea {
            get {
                return ResourceManager.GetString("Guinea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gw.
        /// </summary>
        public static string Guinea_Bissau {
            get {
                return ResourceManager.GetString("Guinea_Bissau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gy.
        /// </summary>
        public static string Guyana {
            get {
                return ResourceManager.GetString("Guyana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ht.
        /// </summary>
        public static string Haiti {
            get {
                return ResourceManager.GetString("Haiti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hm.
        /// </summary>
        public static string Heard_Island_and_McDonald_Islands {
            get {
                return ResourceManager.GetString("Heard_Island_and_McDonald_Islands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to va.
        /// </summary>
        public static string Holy_See_Vatican_City_State {
            get {
                return ResourceManager.GetString("Holy_See_Vatican_City_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hn.
        /// </summary>
        public static string Honduras {
            get {
                return ResourceManager.GetString("Honduras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hk.
        /// </summary>
        public static string Hong_Kong {
            get {
                return ResourceManager.GetString("Hong_Kong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hu.
        /// </summary>
        public static string Hungary {
            get {
                return ResourceManager.GetString("Hungary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is.
        /// </summary>
        public static string Iceland {
            get {
                return ResourceManager.GetString("Iceland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in.
        /// </summary>
        public static string India {
            get {
                return ResourceManager.GetString("India", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id.
        /// </summary>
        public static string Indonesia {
            get {
                return ResourceManager.GetString("Indonesia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ir.
        /// </summary>
        public static string Iran {
            get {
                return ResourceManager.GetString("Iran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iq.
        /// </summary>
        public static string Iraq {
            get {
                return ResourceManager.GetString("Iraq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ie.
        /// </summary>
        public static string Ireland {
            get {
                return ResourceManager.GetString("Ireland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to im.
        /// </summary>
        public static string Isle_of_Man {
            get {
                return ResourceManager.GetString("Isle_of_Man", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to il.
        /// </summary>
        public static string Israel {
            get {
                return ResourceManager.GetString("Israel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to it.
        /// </summary>
        public static string Italy {
            get {
                return ResourceManager.GetString("Italy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jm.
        /// </summary>
        public static string Jamaica {
            get {
                return ResourceManager.GetString("Jamaica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jp.
        /// </summary>
        public static string Japan {
            get {
                return ResourceManager.GetString("Japan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to je.
        /// </summary>
        public static string Jersey {
            get {
                return ResourceManager.GetString("Jersey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jo.
        /// </summary>
        public static string Jordan {
            get {
                return ResourceManager.GetString("Jordan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kz.
        /// </summary>
        public static string Kazakhstan {
            get {
                return ResourceManager.GetString("Kazakhstan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ke.
        /// </summary>
        public static string Kenya {
            get {
                return ResourceManager.GetString("Kenya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ki.
        /// </summary>
        public static string Kiribati {
            get {
                return ResourceManager.GetString("Kiribati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kw.
        /// </summary>
        public static string Kuwait {
            get {
                return ResourceManager.GetString("Kuwait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kg.
        /// </summary>
        public static string Kyrgyzstan {
            get {
                return ResourceManager.GetString("Kyrgyzstan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to la.
        /// </summary>
        public static string Lao_Peoples {
            get {
                return ResourceManager.GetString("Lao_Peoples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lv.
        /// </summary>
        public static string Latvia {
            get {
                return ResourceManager.GetString("Latvia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lb.
        /// </summary>
        public static string Lebanon {
            get {
                return ResourceManager.GetString("Lebanon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ls.
        /// </summary>
        public static string Lesotho {
            get {
                return ResourceManager.GetString("Lesotho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lr.
        /// </summary>
        public static string Liberia {
            get {
                return ResourceManager.GetString("Liberia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ly.
        /// </summary>
        public static string Libyan_Arab_Jamahiriya {
            get {
                return ResourceManager.GetString("Libyan_Arab_Jamahiriya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to li.
        /// </summary>
        public static string Liechtenstein {
            get {
                return ResourceManager.GetString("Liechtenstein", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lt.
        /// </summary>
        public static string Lithuania {
            get {
                return ResourceManager.GetString("Lithuania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lu.
        /// </summary>
        public static string Luxembourg {
            get {
                return ResourceManager.GetString("Luxembourg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mo.
        /// </summary>
        public static string Macao {
            get {
                return ResourceManager.GetString("Macao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mk.
        /// </summary>
        public static string Macedonia {
            get {
                return ResourceManager.GetString("Macedonia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mg.
        /// </summary>
        public static string Madagascar {
            get {
                return ResourceManager.GetString("Madagascar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mw.
        /// </summary>
        public static string Malawi {
            get {
                return ResourceManager.GetString("Malawi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to my.
        /// </summary>
        public static string Malaysia {
            get {
                return ResourceManager.GetString("Malaysia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mv.
        /// </summary>
        public static string Maldives {
            get {
                return ResourceManager.GetString("Maldives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ml.
        /// </summary>
        public static string Mali {
            get {
                return ResourceManager.GetString("Mali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mt.
        /// </summary>
        public static string Malta {
            get {
                return ResourceManager.GetString("Malta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mh.
        /// </summary>
        public static string Marshall_Islands {
            get {
                return ResourceManager.GetString("Marshall_Islands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mq.
        /// </summary>
        public static string Martinique {
            get {
                return ResourceManager.GetString("Martinique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mr.
        /// </summary>
        public static string Mauritania {
            get {
                return ResourceManager.GetString("Mauritania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mu.
        /// </summary>
        public static string Mauritius {
            get {
                return ResourceManager.GetString("Mauritius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yt.
        /// </summary>
        public static string Mayotte {
            get {
                return ResourceManager.GetString("Mayotte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mx.
        /// </summary>
        public static string Mexico {
            get {
                return ResourceManager.GetString("Mexico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fm.
        /// </summary>
        public static string Micronesia {
            get {
                return ResourceManager.GetString("Micronesia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to md.
        /// </summary>
        public static string Moldova_Republic_of {
            get {
                return ResourceManager.GetString("Moldova_Republic_of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mc.
        /// </summary>
        public static string Monaco {
            get {
                return ResourceManager.GetString("Monaco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mn.
        /// </summary>
        public static string Mongolia {
            get {
                return ResourceManager.GetString("Mongolia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to me.
        /// </summary>
        public static string Montenegro {
            get {
                return ResourceManager.GetString("Montenegro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ms.
        /// </summary>
        public static string Montserrat {
            get {
                return ResourceManager.GetString("Montserrat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ma.
        /// </summary>
        public static string Morocco {
            get {
                return ResourceManager.GetString("Morocco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mz.
        /// </summary>
        public static string Mozambique {
            get {
                return ResourceManager.GetString("Mozambique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mm.
        /// </summary>
        public static string Myanmar {
            get {
                return ResourceManager.GetString("Myanmar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to na.
        /// </summary>
        public static string Namibia {
            get {
                return ResourceManager.GetString("Namibia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nr.
        /// </summary>
        public static string Nauru {
            get {
                return ResourceManager.GetString("Nauru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to np.
        /// </summary>
        public static string Nepal {
            get {
                return ResourceManager.GetString("Nepal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nl.
        /// </summary>
        public static string Netherlands {
            get {
                return ResourceManager.GetString("Netherlands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nc.
        /// </summary>
        public static string New_Caledonia {
            get {
                return ResourceManager.GetString("New_Caledonia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nz.
        /// </summary>
        public static string New_Zealand {
            get {
                return ResourceManager.GetString("New_Zealand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ni.
        /// </summary>
        public static string Nicaragua {
            get {
                return ResourceManager.GetString("Nicaragua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ne.
        /// </summary>
        public static string Niger {
            get {
                return ResourceManager.GetString("Niger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ng.
        /// </summary>
        public static string Nigeria {
            get {
                return ResourceManager.GetString("Nigeria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nu.
        /// </summary>
        public static string Niue {
            get {
                return ResourceManager.GetString("Niue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nf.
        /// </summary>
        public static string Norfolk_Island {
            get {
                return ResourceManager.GetString("Norfolk_Island", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kr.
        /// </summary>
        public static string North_Korea {
            get {
                return ResourceManager.GetString("North_Korea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mp.
        /// </summary>
        public static string Northern_Mariana_Islands {
            get {
                return ResourceManager.GetString("Northern_Mariana_Islands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.
        /// </summary>
        public static string Norway {
            get {
                return ResourceManager.GetString("Norway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to om.
        /// </summary>
        public static string Oman {
            get {
                return ResourceManager.GetString("Oman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pk.
        /// </summary>
        public static string Pakistan {
            get {
                return ResourceManager.GetString("Pakistan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pw.
        /// </summary>
        public static string Palau {
            get {
                return ResourceManager.GetString("Palau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ps.
        /// </summary>
        public static string Palestine {
            get {
                return ResourceManager.GetString("Palestine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pa.
        /// </summary>
        public static string Panama {
            get {
                return ResourceManager.GetString("Panama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pg.
        /// </summary>
        public static string Papua_New_Guinea {
            get {
                return ResourceManager.GetString("Papua_New_Guinea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to py.
        /// </summary>
        public static string Paraguay {
            get {
                return ResourceManager.GetString("Paraguay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pe.
        /// </summary>
        public static string Peru {
            get {
                return ResourceManager.GetString("Peru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ph.
        /// </summary>
        public static string Philippines {
            get {
                return ResourceManager.GetString("Philippines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pn.
        /// </summary>
        public static string Pitcairn {
            get {
                return ResourceManager.GetString("Pitcairn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pl.
        /// </summary>
        public static string Poland {
            get {
                return ResourceManager.GetString("Poland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pt.
        /// </summary>
        public static string Portugal {
            get {
                return ResourceManager.GetString("Portugal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pr.
        /// </summary>
        public static string Puerto_Rico {
            get {
                return ResourceManager.GetString("Puerto_Rico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to qa.
        /// </summary>
        public static string Qatar {
            get {
                return ResourceManager.GetString("Qatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ro.
        /// </summary>
        public static string Romania {
            get {
                return ResourceManager.GetString("Romania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to re.
        /// </summary>
        public static string Runion {
            get {
                return ResourceManager.GetString("Runion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ru.
        /// </summary>
        public static string Russian_Federation {
            get {
                return ResourceManager.GetString("Russian_Federation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rw.
        /// </summary>
        public static string Rwanda {
            get {
                return ResourceManager.GetString("Rwanda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sh.
        /// </summary>
        public static string Saint_Helena {
            get {
                return ResourceManager.GetString("Saint_Helena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kn.
        /// </summary>
        public static string Saint_Kitts_and_Nevis {
            get {
                return ResourceManager.GetString("Saint_Kitts_and_Nevis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lc.
        /// </summary>
        public static string Saint_Lucia {
            get {
                return ResourceManager.GetString("Saint_Lucia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mf.
        /// </summary>
        public static string Saint_Martin_French_part {
            get {
                return ResourceManager.GetString("Saint_Martin_French_part", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pm.
        /// </summary>
        public static string Saint_Pierre_and_Miquelon {
            get {
                return ResourceManager.GetString("Saint_Pierre_and_Miquelon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vc.
        /// </summary>
        public static string Saint_Vincent_and_the_Grenadines {
            get {
                return ResourceManager.GetString("Saint_Vincent_and_the_Grenadines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ws.
        /// </summary>
        public static string Samoa {
            get {
                return ResourceManager.GetString("Samoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sm.
        /// </summary>
        public static string San_Marino {
            get {
                return ResourceManager.GetString("San_Marino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to st.
        /// </summary>
        public static string Sao_Tome_and_Principe {
            get {
                return ResourceManager.GetString("Sao_Tome_and_Principe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sa.
        /// </summary>
        public static string Saudi_Arabia {
            get {
                return ResourceManager.GetString("Saudi_Arabia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sn.
        /// </summary>
        public static string Senegal {
            get {
                return ResourceManager.GetString("Senegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rs.
        /// </summary>
        public static string Serbia {
            get {
                return ResourceManager.GetString("Serbia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sc.
        /// </summary>
        public static string Seychelles {
            get {
                return ResourceManager.GetString("Seychelles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sl.
        /// </summary>
        public static string Sierra_Leone {
            get {
                return ResourceManager.GetString("Sierra_Leone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sg.
        /// </summary>
        public static string Singapore {
            get {
                return ResourceManager.GetString("Singapore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sk.
        /// </summary>
        public static string Slovakia {
            get {
                return ResourceManager.GetString("Slovakia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to si.
        /// </summary>
        public static string Slovenia {
            get {
                return ResourceManager.GetString("Slovenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sb.
        /// </summary>
        public static string Solomon_Islands {
            get {
                return ResourceManager.GetString("Solomon_Islands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to so.
        /// </summary>
        public static string Somalia {
            get {
                return ResourceManager.GetString("Somalia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to za.
        /// </summary>
        public static string South_Africa {
            get {
                return ResourceManager.GetString("South_Africa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gs.
        /// </summary>
        public static string South_Georgia_and_the_South_Sandwich_Islands {
            get {
                return ResourceManager.GetString("South_Georgia_and_the_South_Sandwich_Islands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kp.
        /// </summary>
        public static string South_Korea {
            get {
                return ResourceManager.GetString("South_Korea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to es.
        /// </summary>
        public static string Spain {
            get {
                return ResourceManager.GetString("Spain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lk.
        /// </summary>
        public static string Sri_Lanka {
            get {
                return ResourceManager.GetString("Sri_Lanka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sd.
        /// </summary>
        public static string Sudan {
            get {
                return ResourceManager.GetString("Sudan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sr.
        /// </summary>
        public static string Suriname {
            get {
                return ResourceManager.GetString("Suriname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sj.
        /// </summary>
        public static string Svalbard_and_Jan_Mayen {
            get {
                return ResourceManager.GetString("Svalbard_and_Jan_Mayen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sz.
        /// </summary>
        public static string Swaziland {
            get {
                return ResourceManager.GetString("Swaziland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to se.
        /// </summary>
        public static string Sweden {
            get {
                return ResourceManager.GetString("Sweden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sy.
        /// </summary>
        public static string Syrian_Arab_Republic {
            get {
                return ResourceManager.GetString("Syrian_Arab_Republic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tw.
        /// </summary>
        public static string Taiwan_Province_of_China {
            get {
                return ResourceManager.GetString("Taiwan_Province_of_China", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tj.
        /// </summary>
        public static string Tajikistan {
            get {
                return ResourceManager.GetString("Tajikistan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tz.
        /// </summary>
        public static string Tanzania {
            get {
                return ResourceManager.GetString("Tanzania", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to th.
        /// </summary>
        public static string Thailand {
            get {
                return ResourceManager.GetString("Thailand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tl.
        /// </summary>
        public static string Timor_Leste {
            get {
                return ResourceManager.GetString("Timor_Leste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tg.
        /// </summary>
        public static string Togo {
            get {
                return ResourceManager.GetString("Togo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tk.
        /// </summary>
        public static string Tokelau {
            get {
                return ResourceManager.GetString("Tokelau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        public static string Tonga {
            get {
                return ResourceManager.GetString("Tonga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tt.
        /// </summary>
        public static string Trinidad_and_Tobago {
            get {
                return ResourceManager.GetString("Trinidad_and_Tobago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tn.
        /// </summary>
        public static string Tunisia {
            get {
                return ResourceManager.GetString("Tunisia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tr.
        /// </summary>
        public static string Turkey {
            get {
                return ResourceManager.GetString("Turkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tm.
        /// </summary>
        public static string Turkmenistan {
            get {
                return ResourceManager.GetString("Turkmenistan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tc.
        /// </summary>
        public static string Turks_and_Caicos_Islands {
            get {
                return ResourceManager.GetString("Turks_and_Caicos_Islands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tv.
        /// </summary>
        public static string Tuvalu {
            get {
                return ResourceManager.GetString("Tuvalu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ug.
        /// </summary>
        public static string Uganda {
            get {
                return ResourceManager.GetString("Uganda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ua.
        /// </summary>
        public static string Ukraine {
            get {
                return ResourceManager.GetString("Ukraine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gb.
        /// </summary>
        public static string United_Kingdom {
            get {
                return ResourceManager.GetString("United_Kingdom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to us.
        /// </summary>
        public static string United_States {
            get {
                return ResourceManager.GetString("United_States", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to um.
        /// </summary>
        public static string United_States_Minor_Outlying_Islands {
            get {
                return ResourceManager.GetString("United_States_Minor_Outlying_Islands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uy.
        /// </summary>
        public static string Uruguay {
            get {
                return ResourceManager.GetString("Uruguay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uz.
        /// </summary>
        public static string Uzbekistan {
            get {
                return ResourceManager.GetString("Uzbekistan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vu.
        /// </summary>
        public static string Vanuatu {
            get {
                return ResourceManager.GetString("Vanuatu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ve.
        /// </summary>
        public static string Venezuela {
            get {
                return ResourceManager.GetString("Venezuela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vn.
        /// </summary>
        public static string Viet_Nam {
            get {
                return ResourceManager.GetString("Viet_Nam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vg.
        /// </summary>
        public static string Virgin_Islands_British {
            get {
                return ResourceManager.GetString("Virgin_Islands_British", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vi.
        /// </summary>
        public static string Virgin_Islands_US {
            get {
                return ResourceManager.GetString("Virgin_Islands_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wf.
        /// </summary>
        public static string Wallis_and_Futuna {
            get {
                return ResourceManager.GetString("Wallis_and_Futuna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eh.
        /// </summary>
        public static string Western_Sahara {
            get {
                return ResourceManager.GetString("Western_Sahara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ye.
        /// </summary>
        public static string Yemen {
            get {
                return ResourceManager.GetString("Yemen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zm.
        /// </summary>
        public static string Zambia {
            get {
                return ResourceManager.GetString("Zambia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zw.
        /// </summary>
        public static string Zimbabwe {
            get {
                return ResourceManager.GetString("Zimbabwe", resourceCulture);
            }
        }
    }
}
