//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoogleSearchAPI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NewsEdition {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NewsEdition() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GoogleSearchAPI.Resources.NewsEdition", typeof(NewsEdition).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ar_me.
        /// </summary>
        public static string Arab_World {
            get {
                return ResourceManager.GetString("Arab_World", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to es_ar.
        /// </summary>
        public static string Argentina {
            get {
                return ResourceManager.GetString("Argentina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to au.
        /// </summary>
        public static string Australia {
            get {
                return ResourceManager.GetString("Australia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de_at.
        /// </summary>
        public static string Austria {
            get {
                return ResourceManager.GetString("Austria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nl_be.
        /// </summary>
        public static string Belgium_Dutch {
            get {
                return ResourceManager.GetString("Belgium_Dutch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fr_be.
        /// </summary>
        public static string Belgium_French {
            get {
                return ResourceManager.GetString("Belgium_French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en_bw.
        /// </summary>
        public static string Botswana_English {
            get {
                return ResourceManager.GetString("Botswana_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to es_br.
        /// </summary>
        public static string Brazil {
            get {
                return ResourceManager.GetString("Brazil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ca.
        /// </summary>
        public static string Canada_English {
            get {
                return ResourceManager.GetString("Canada_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fr_ca.
        /// </summary>
        public static string Canada_French {
            get {
                return ResourceManager.GetString("Canada_French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to es_cl.
        /// </summary>
        public static string Chile {
            get {
                return ResourceManager.GetString("Chile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cn.
        /// </summary>
        public static string China {
            get {
                return ResourceManager.GetString("China", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to es_co.
        /// </summary>
        public static string Colombia {
            get {
                return ResourceManager.GetString("Colombia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to es_cu.
        /// </summary>
        public static string Cuba {
            get {
                return ResourceManager.GetString("Cuba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cs_cz.
        /// </summary>
        public static string Czech {
            get {
                return ResourceManager.GetString("Czech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ar_eg.
        /// </summary>
        public static string Egypt {
            get {
                return ResourceManager.GetString("Egypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en_et.
        /// </summary>
        public static string Ethiopia_English {
            get {
                return ResourceManager.GetString("Ethiopia_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fr.
        /// </summary>
        public static string France {
            get {
                return ResourceManager.GetString("France", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de.
        /// </summary>
        public static string Germany {
            get {
                return ResourceManager.GetString("Germany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en_gh.
        /// </summary>
        public static string Ghana_English {
            get {
                return ResourceManager.GetString("Ghana_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nl_nl.
        /// </summary>
        public static string Holland {
            get {
                return ResourceManager.GetString("Holland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hk.
        /// </summary>
        public static string Hong_Kong {
            get {
                return ResourceManager.GetString("Hong_Kong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hu.
        /// </summary>
        public static string Hungary {
            get {
                return ResourceManager.GetString("Hungary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in.
        /// </summary>
        public static string India {
            get {
                return ResourceManager.GetString("India", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id.
        /// </summary>
        public static string Indonesia {
            get {
                return ResourceManager.GetString("Indonesia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en_ie.
        /// </summary>
        public static string Ireland_English {
            get {
                return ResourceManager.GetString("Ireland_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en_il.
        /// </summary>
        public static string Israel_English {
            get {
                return ResourceManager.GetString("Israel_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iw_il.
        /// </summary>
        public static string Israel_Hebrew {
            get {
                return ResourceManager.GetString("Israel_Hebrew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to it.
        /// </summary>
        public static string Italy {
            get {
                return ResourceManager.GetString("Italy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jp.
        /// </summary>
        public static string Japan {
            get {
                return ResourceManager.GetString("Japan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ke.
        /// </summary>
        public static string Kenya_English {
            get {
                return ResourceManager.GetString("Kenya_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kr.
        /// </summary>
        public static string Korea {
            get {
                return ResourceManager.GetString("Korea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ar_sa.
        /// </summary>
        public static string KSA {
            get {
                return ResourceManager.GetString("KSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ar_lb.
        /// </summary>
        public static string Lebanon {
            get {
                return ResourceManager.GetString("Lebanon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en_my.
        /// </summary>
        public static string Malaysia_English {
            get {
                return ResourceManager.GetString("Malaysia_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to es_mx.
        /// </summary>
        public static string Mexico {
            get {
                return ResourceManager.GetString("Mexico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en_na.
        /// </summary>
        public static string Namibia_English {
            get {
                return ResourceManager.GetString("Namibia_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nz.
        /// </summary>
        public static string New_Zealand {
            get {
                return ResourceManager.GetString("New_Zealand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en_ng.
        /// </summary>
        public static string Nigeria {
            get {
                return ResourceManager.GetString("Nigeria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no_no.
        /// </summary>
        public static string Norway {
            get {
                return ResourceManager.GetString("Norway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en_pk.
        /// </summary>
        public static string Pakistan_English {
            get {
                return ResourceManager.GetString("Pakistan_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to es_pe.
        /// </summary>
        public static string Peru {
            get {
                return ResourceManager.GetString("Peru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en_ph.
        /// </summary>
        public static string Philippines_English {
            get {
                return ResourceManager.GetString("Philippines_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pl_pl.
        /// </summary>
        public static string Poland {
            get {
                return ResourceManager.GetString("Poland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pt-PT_pt.
        /// </summary>
        public static string Portugal {
            get {
                return ResourceManager.GetString("Portugal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ru_ru.
        /// </summary>
        public static string Russia {
            get {
                return ResourceManager.GetString("Russia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fr_sn.
        /// </summary>
        public static string Senegal_French {
            get {
                return ResourceManager.GetString("Senegal_French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en_sg.
        /// </summary>
        public static string Singapore_English {
            get {
                return ResourceManager.GetString("Singapore_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to es.
        /// </summary>
        public static string Spain {
            get {
                return ResourceManager.GetString("Spain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sv_se.
        /// </summary>
        public static string Sweden {
            get {
                return ResourceManager.GetString("Sweden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de_ch.
        /// </summary>
        public static string Switzerland_German {
            get {
                return ResourceManager.GetString("Switzerland_German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tw.
        /// </summary>
        public static string Taiwan {
            get {
                return ResourceManager.GetString("Taiwan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en_tz.
        /// </summary>
        public static string Tanzania_English {
            get {
                return ResourceManager.GetString("Tanzania_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to th.
        /// </summary>
        public static string Thailand {
            get {
                return ResourceManager.GetString("Thailand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tr_tr.
        /// </summary>
        public static string Turkey {
            get {
                return ResourceManager.GetString("Turkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ar_ae.
        /// </summary>
        public static string UAE {
            get {
                return ResourceManager.GetString("UAE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en_ug.
        /// </summary>
        public static string Uganda_English {
            get {
                return ResourceManager.GetString("Uganda_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ru_ua.
        /// </summary>
        public static string Ukraine_Russian {
            get {
                return ResourceManager.GetString("Ukraine_Russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uk_ua.
        /// </summary>
        public static string Ukraine_Ukraine {
            get {
                return ResourceManager.GetString("Ukraine_Ukraine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uk.
        /// </summary>
        public static string United_Kingdom {
            get {
                return ResourceManager.GetString("United_Kingdom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to us.
        /// </summary>
        public static string United_States {
            get {
                return ResourceManager.GetString("United_States", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to es_us.
        /// </summary>
        public static string United_States_Spanish {
            get {
                return ResourceManager.GetString("United_States_Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to es_ve.
        /// </summary>
        public static string Venezuela {
            get {
                return ResourceManager.GetString("Venezuela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vi_vn.
        /// </summary>
        public static string Vietnam {
            get {
                return ResourceManager.GetString("Vietnam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en_zw.
        /// </summary>
        public static string Zimbabwe_English {
            get {
                return ResourceManager.GetString("Zimbabwe_English", resourceCulture);
            }
        }
    }
}
