//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoogleSearchAPI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TranslateLanguages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TranslateLanguages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GoogleSearchAPI.Resources.TranslateLanguages", typeof(TranslateLanguages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to af.
        /// </summary>
        public static string AFRIKAANS {
            get {
                return ResourceManager.GetString("AFRIKAANS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sq.
        /// </summary>
        public static string ALBANIAN {
            get {
                return ResourceManager.GetString("ALBANIAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to am.
        /// </summary>
        public static string AMHARIC {
            get {
                return ResourceManager.GetString("AMHARIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ar.
        /// </summary>
        public static string ARABIC {
            get {
                return ResourceManager.GetString("ARABIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hy.
        /// </summary>
        public static string ARMENIAN {
            get {
                return ResourceManager.GetString("ARMENIAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to az.
        /// </summary>
        public static string AZERBAIJANI {
            get {
                return ResourceManager.GetString("AZERBAIJANI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eu.
        /// </summary>
        public static string BASQUE {
            get {
                return ResourceManager.GetString("BASQUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to be.
        /// </summary>
        public static string BELARUSIAN {
            get {
                return ResourceManager.GetString("BELARUSIAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bn.
        /// </summary>
        public static string BENGALI {
            get {
                return ResourceManager.GetString("BENGALI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bh.
        /// </summary>
        public static string BIHARI {
            get {
                return ResourceManager.GetString("BIHARI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to br.
        /// </summary>
        public static string BRETON {
            get {
                return ResourceManager.GetString("BRETON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bg.
        /// </summary>
        public static string BULGARIAN {
            get {
                return ResourceManager.GetString("BULGARIAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to my.
        /// </summary>
        public static string BURMESE {
            get {
                return ResourceManager.GetString("BURMESE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ca.
        /// </summary>
        public static string CATALAN {
            get {
                return ResourceManager.GetString("CATALAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to chr.
        /// </summary>
        public static string CHEROKEE {
            get {
                return ResourceManager.GetString("CHEROKEE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zh.
        /// </summary>
        public static string CHINESE {
            get {
                return ResourceManager.GetString("CHINESE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zh-CN.
        /// </summary>
        public static string CHINESE_SIMPLIFIED {
            get {
                return ResourceManager.GetString("CHINESE_SIMPLIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zh-TW.
        /// </summary>
        public static string CHINESE_TRADITIONAL {
            get {
                return ResourceManager.GetString("CHINESE_TRADITIONAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to co.
        /// </summary>
        public static string CORSICAN {
            get {
                return ResourceManager.GetString("CORSICAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hr.
        /// </summary>
        public static string CROATIAN {
            get {
                return ResourceManager.GetString("CROATIAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cs.
        /// </summary>
        public static string CZECH {
            get {
                return ResourceManager.GetString("CZECH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to da.
        /// </summary>
        public static string DANISH {
            get {
                return ResourceManager.GetString("DANISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dv.
        /// </summary>
        public static string DHIVEHI {
            get {
                return ResourceManager.GetString("DHIVEHI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nl.
        /// </summary>
        public static string DUTCH {
            get {
                return ResourceManager.GetString("DUTCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        public static string ENGLISH {
            get {
                return ResourceManager.GetString("ENGLISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eo.
        /// </summary>
        public static string ESPERANTO {
            get {
                return ResourceManager.GetString("ESPERANTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to et.
        /// </summary>
        public static string ESTONIAN {
            get {
                return ResourceManager.GetString("ESTONIAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fo.
        /// </summary>
        public static string FAROESE {
            get {
                return ResourceManager.GetString("FAROESE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tl.
        /// </summary>
        public static string FILIPINO {
            get {
                return ResourceManager.GetString("FILIPINO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fi.
        /// </summary>
        public static string FINNISH {
            get {
                return ResourceManager.GetString("FINNISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fr.
        /// </summary>
        public static string FRENCH {
            get {
                return ResourceManager.GetString("FRENCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fy.
        /// </summary>
        public static string FRISIAN {
            get {
                return ResourceManager.GetString("FRISIAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gl.
        /// </summary>
        public static string GALICIAN {
            get {
                return ResourceManager.GetString("GALICIAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ka.
        /// </summary>
        public static string GEORGIAN {
            get {
                return ResourceManager.GetString("GEORGIAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to de.
        /// </summary>
        public static string GERMAN {
            get {
                return ResourceManager.GetString("GERMAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to el.
        /// </summary>
        public static string GREEK {
            get {
                return ResourceManager.GetString("GREEK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gu.
        /// </summary>
        public static string GUJARATI {
            get {
                return ResourceManager.GetString("GUJARATI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ht.
        /// </summary>
        public static string HAITIAN_CREOLE {
            get {
                return ResourceManager.GetString("HAITIAN_CREOLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iw.
        /// </summary>
        public static string HEBREW {
            get {
                return ResourceManager.GetString("HEBREW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hi.
        /// </summary>
        public static string HINDI {
            get {
                return ResourceManager.GetString("HINDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hu.
        /// </summary>
        public static string HUNGARIAN {
            get {
                return ResourceManager.GetString("HUNGARIAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is.
        /// </summary>
        public static string ICELANDIC {
            get {
                return ResourceManager.GetString("ICELANDIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id.
        /// </summary>
        public static string INDONESIAN {
            get {
                return ResourceManager.GetString("INDONESIAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iu.
        /// </summary>
        public static string INUKTITUT {
            get {
                return ResourceManager.GetString("INUKTITUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ga.
        /// </summary>
        public static string IRISH {
            get {
                return ResourceManager.GetString("IRISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to it.
        /// </summary>
        public static string ITALIAN {
            get {
                return ResourceManager.GetString("ITALIAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ja.
        /// </summary>
        public static string JAPANESE {
            get {
                return ResourceManager.GetString("JAPANESE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jw.
        /// </summary>
        public static string JAVANESE {
            get {
                return ResourceManager.GetString("JAVANESE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kn.
        /// </summary>
        public static string KANNADA {
            get {
                return ResourceManager.GetString("KANNADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kk.
        /// </summary>
        public static string KAZAKH {
            get {
                return ResourceManager.GetString("KAZAKH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to km.
        /// </summary>
        public static string KHMER {
            get {
                return ResourceManager.GetString("KHMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ko.
        /// </summary>
        public static string KOREAN {
            get {
                return ResourceManager.GetString("KOREAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ku.
        /// </summary>
        public static string KURDISH {
            get {
                return ResourceManager.GetString("KURDISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ky.
        /// </summary>
        public static string KYRGYZ {
            get {
                return ResourceManager.GetString("KYRGYZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lo.
        /// </summary>
        public static string LAO {
            get {
                return ResourceManager.GetString("LAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to la.
        /// </summary>
        public static string LATIN {
            get {
                return ResourceManager.GetString("LATIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lv.
        /// </summary>
        public static string LATVIAN {
            get {
                return ResourceManager.GetString("LATVIAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lt.
        /// </summary>
        public static string LITHUANIAN {
            get {
                return ResourceManager.GetString("LITHUANIAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lb.
        /// </summary>
        public static string LUXEMBOURGISH {
            get {
                return ResourceManager.GetString("LUXEMBOURGISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mk.
        /// </summary>
        public static string MACEDONIAN {
            get {
                return ResourceManager.GetString("MACEDONIAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ms.
        /// </summary>
        public static string MALAY {
            get {
                return ResourceManager.GetString("MALAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ml.
        /// </summary>
        public static string MALAYALAM {
            get {
                return ResourceManager.GetString("MALAYALAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mt.
        /// </summary>
        public static string MALTESE {
            get {
                return ResourceManager.GetString("MALTESE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mi.
        /// </summary>
        public static string MAORI {
            get {
                return ResourceManager.GetString("MAORI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mr.
        /// </summary>
        public static string MARATHI {
            get {
                return ResourceManager.GetString("MARATHI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mn.
        /// </summary>
        public static string MONGOLIAN {
            get {
                return ResourceManager.GetString("MONGOLIAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ne.
        /// </summary>
        public static string NEPALI {
            get {
                return ResourceManager.GetString("NEPALI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.
        /// </summary>
        public static string NORWEGIAN {
            get {
                return ResourceManager.GetString("NORWEGIAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to oc.
        /// </summary>
        public static string OCCITAN {
            get {
                return ResourceManager.GetString("OCCITAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        public static string ORIYA {
            get {
                return ResourceManager.GetString("ORIYA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ps.
        /// </summary>
        public static string PASHTO {
            get {
                return ResourceManager.GetString("PASHTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fa.
        /// </summary>
        public static string PERSIAN {
            get {
                return ResourceManager.GetString("PERSIAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pl.
        /// </summary>
        public static string POLISH {
            get {
                return ResourceManager.GetString("POLISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pt.
        /// </summary>
        public static string PORTUGUESE {
            get {
                return ResourceManager.GetString("PORTUGUESE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pt-PT.
        /// </summary>
        public static string PORTUGUESE_PORTUGAL {
            get {
                return ResourceManager.GetString("PORTUGUESE_PORTUGAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pa.
        /// </summary>
        public static string PUNJABI {
            get {
                return ResourceManager.GetString("PUNJABI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to qu.
        /// </summary>
        public static string QUECHUA {
            get {
                return ResourceManager.GetString("QUECHUA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ro.
        /// </summary>
        public static string ROMANIAN {
            get {
                return ResourceManager.GetString("ROMANIAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ru.
        /// </summary>
        public static string RUSSIAN {
            get {
                return ResourceManager.GetString("RUSSIAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sa.
        /// </summary>
        public static string SANSKRIT {
            get {
                return ResourceManager.GetString("SANSKRIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gd.
        /// </summary>
        public static string SCOTS_GAELIC {
            get {
                return ResourceManager.GetString("SCOTS_GAELIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sr.
        /// </summary>
        public static string SERBIAN {
            get {
                return ResourceManager.GetString("SERBIAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sd.
        /// </summary>
        public static string SINDHI {
            get {
                return ResourceManager.GetString("SINDHI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to si.
        /// </summary>
        public static string SINHALESE {
            get {
                return ResourceManager.GetString("SINHALESE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sk.
        /// </summary>
        public static string SLOVAK {
            get {
                return ResourceManager.GetString("SLOVAK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sl.
        /// </summary>
        public static string SLOVENIAN {
            get {
                return ResourceManager.GetString("SLOVENIAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to es.
        /// </summary>
        public static string SPANISH {
            get {
                return ResourceManager.GetString("SPANISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to su.
        /// </summary>
        public static string SUNDANESE {
            get {
                return ResourceManager.GetString("SUNDANESE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sw.
        /// </summary>
        public static string SWAHILI {
            get {
                return ResourceManager.GetString("SWAHILI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sv.
        /// </summary>
        public static string SWEDISH {
            get {
                return ResourceManager.GetString("SWEDISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to syr.
        /// </summary>
        public static string SYRIAC {
            get {
                return ResourceManager.GetString("SYRIAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tg.
        /// </summary>
        public static string TAJIK {
            get {
                return ResourceManager.GetString("TAJIK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ta.
        /// </summary>
        public static string TAMIL {
            get {
                return ResourceManager.GetString("TAMIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tt.
        /// </summary>
        public static string TATAR {
            get {
                return ResourceManager.GetString("TATAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to te.
        /// </summary>
        public static string TELUGU {
            get {
                return ResourceManager.GetString("TELUGU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to th.
        /// </summary>
        public static string THAI {
            get {
                return ResourceManager.GetString("THAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bo.
        /// </summary>
        public static string TIBETAN {
            get {
                return ResourceManager.GetString("TIBETAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        public static string TONGA {
            get {
                return ResourceManager.GetString("TONGA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tr.
        /// </summary>
        public static string TURKISH {
            get {
                return ResourceManager.GetString("TURKISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ug.
        /// </summary>
        public static string UIGHUR {
            get {
                return ResourceManager.GetString("UIGHUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uk.
        /// </summary>
        public static string UKRAINIAN {
            get {
                return ResourceManager.GetString("UKRAINIAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ur.
        /// </summary>
        public static string URDU {
            get {
                return ResourceManager.GetString("URDU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uz.
        /// </summary>
        public static string UZBEK {
            get {
                return ResourceManager.GetString("UZBEK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vi.
        /// </summary>
        public static string VIETNAMESE {
            get {
                return ResourceManager.GetString("VIETNAMESE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cy.
        /// </summary>
        public static string WELSH {
            get {
                return ResourceManager.GetString("WELSH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yi.
        /// </summary>
        public static string YIDDISH {
            get {
                return ResourceManager.GetString("YIDDISH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yo.
        /// </summary>
        public static string YORUBA {
            get {
                return ResourceManager.GetString("YORUBA", resourceCulture);
            }
        }
    }
}
